name: Security audit

on:
  push:
    paths:
      - '.github/workflows/audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  pull_request:
    paths:
      - '.github/workflows/audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'
  schedule:
    - cron: '21 20 2 * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # v1.2.7
